In [2]:
print("hello")

hello


# 마크다운
## 안녕

In [4]:
import numpy as np

In [10]:
%%time
x = np.arange(1, 10001)
x2 = np.arange(10001, 20001)
x3 = np.zeros_like(x)

for i in range(10000):
    x3[i] = x[i]+x2[i]

Wall time: 15.4 ms


In [11]:
%%time
x3 = x+x2

Wall time: 0 ns


In [13]:
np.exp(2)

7.38905609893065

In [15]:
x = np.array([4, 5, 6, 7])
x.argmin()    # 최소값의 index
x.argmax()    # 최대값의 index

3

In [16]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [19]:
x.sum()
x.sum(axis=0)    # 열 단위로 합이 구해진다
x.sum(axis=1)    # 행 단위로 합이 구해진다

array([ 3,  7, 11])

In [22]:
x = np.array([[11, 2], [23, 14], [5, 26]])
print(np.sort(x))    # axis=1일 때와 동일 (행 단위로 오름차순 정렬)
print("*" * 50)
print(np.sort(x, axis=0))    # 열 단위로 오름차순 정렬

[[ 2 11]
 [14 23]
 [ 5 26]]
**************************************************
[[ 5  2]
 [11 14]
 [23 26]]


In [23]:
x

array([[11,  2],
       [23, 14],
       [ 5, 26]])

In [24]:
x = np.array([40, 30, 10, 20])
np.argsort(x)
#   0   1   2   3        2   3   1   0
# [40, 30, 10, 20] ==> [10, 20, 30, 40]
# 즉, argsort는 정렬 후 위치에 원래 index를 출력하는 것

array([2, 3, 1, 0], dtype=int64)