In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

# Multivariable Linear Regression (다중 선형 회귀)

In [2]:
x1data = [70, 90, 88, 95, 75]    # 5명의 3월 모의고사 점수
x2data = [80, 88, 90, 98, 65]    # 5명의 4월 모의고사 점수
x3data = [75, 93, 90, 100, 70]    # 5명의 5월 모의고사 점수
ydata = [150, 185, 180, 200, 140]    # 5명의 실제 수능 점수

In [3]:
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
w1 = tf.Variable(tf.random_normal([1]), name="weight1")
w2 = tf.Variable(tf.random_normal([1]), name="weight2")
w3 = tf.Variable(tf.random_normal([1]), name="weight3")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [4]:
hf = x1 * w1 + x2 * w2 + x3 * w3 + b
cost = tf.reduce_mean(tf.square(hf - y))

In [5]:
train = tf.train.GradientDescentOptimizer(1e-5).minimize(cost)

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict={x1:x1data, x2:x2data, x3:x3data, y:ydata})
    if step % 10 == 0:
        print("step: ", step, ", cost: ", cv, ", prediction: ", hv)

# 실제값: [150           185       180       200       140]
# 예측값: [148.3878  183.45149 180.90034 196.14665 147.95647]

step:  0 , cost:  31472.754 , prediction:  [309.88763 371.43237 367.2476  402.51593 284.80438]
step:  10 , cost:  4.2153234 , prediction:  [154.033   183.73592 181.64104 199.56903 139.42134]
step:  20 , cost:  3.8439102 , prediction:  [153.5026  183.11176 181.0192  198.88896 138.94513]
step:  30 , cost:  3.8243394 , prediction:  [153.49149 183.11296 181.01573 198.88509 138.95331]
step:  40 , cost:  3.8049664 , prediction:  [153.48215 183.11623 181.01436 198.88347 138.96303]
step:  50 , cost:  3.7856884 , prediction:  [153.47284 183.1195  181.01299 198.88188 138.97275]
step:  60 , cost:  3.7666378 , prediction:  [153.46361 183.12277 181.01164 198.8803  138.98242]
step:  70 , cost:  3.747694 , prediction:  [153.45438 183.12602 181.01028 198.87871 138.99203]
step:  80 , cost:  3.7289326 , prediction:  [153.44519 183.12924 181.00891 198.8771  139.0016 ]
step:  90 , cost:  3.710278 , prediction:  [153.43605 183.13249 181.00758 198.87558 139.01115]
step:  100 , cost:  3.6917892 , prediction:

step:  1070 , cost:  2.450495 , prediction:  [152.69911 183.39882 180.89601 198.75674 139.76555]
step:  1080 , cost:  2.44198 , prediction:  [152.693   183.4011  180.89505 198.75584 139.77165]
step:  1090 , cost:  2.4335644 , prediction:  [152.6869  183.40335 180.8941  198.75491 139.77771]
step:  1100 , cost:  2.425177 , prediction:  [152.68083 183.40561 180.89314 198.75401 139.78377]
step:  1110 , cost:  2.4168627 , prediction:  [152.67479 183.40785 180.89217 198.75311 139.78978]
step:  1120 , cost:  2.408625 , prediction:  [152.6688  183.41011 180.89127 198.75226 139.79578]
step:  1130 , cost:  2.4004512 , prediction:  [152.66283 183.41237 180.89032 198.75137 139.80176]
step:  1140 , cost:  2.3923368 , prediction:  [152.65685 183.41457 180.88936 198.75047 139.8077 ]
step:  1150 , cost:  2.3842666 , prediction:  [152.65091 183.41681 180.88846 198.74963 139.8136 ]
step:  1160 , cost:  2.376267 , prediction:  [152.64499 183.419   180.8875  198.74876 139.81949]
step:  1170 , cost:  2.368

## 행렬로 데이터 표현

In [8]:
xdata = [[70, 90, 88, 95, 75], [80, 88, 90, 98, 65], [75, 93, 90, 100, 70]]    # 5명의 3, 4, 5월 모의고사 점수
ydata = [150, 185, 180, 200, 140]    # 5명의 실제 수능 점수

In [9]:
np.shape(xdata)

(3, 5)

In [10]:
# (3, 5) -> (5, 3)
xdata = np.transpose(xdata)
np.shape(xdata)

(5, 3)

In [11]:
ydata = [[150], [185], [180], [200], [140]]
np.shape(ydata)

(5, 1)

In [12]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [13]:
# hf = x * w + b  이렇게 쓰면 안됨
hf = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-5).minimize(cost)

In [14]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [15]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    if step % 10 == 0:
        print("step: ", step, ", cost: ", cv, ", prediction: ", hv)

step:  0 , cost:  54725.043 , prediction:  [[-60.026394]
 [-61.691113]
 [-66.06944 ]
 [-69.73539 ]
 [-48.01672 ]]
step:  10 , cost:  8.159913 , prediction:  [[145.49217]
 [185.80989]
 [178.6768 ]
 [197.87761]
 [143.68344]]
step:  20 , cost:  7.4846725 , prediction:  [[146.19582]
 [186.6321 ]
 [179.49709]
 [198.77586]
 [144.30539]]
step:  30 , cost:  7.421489 , prediction:  [[146.2147 ]
 [186.62971]
 [179.50194]
 [198.7825 ]
 [144.28867]]
step:  40 , cost:  7.3588305 , prediction:  [[146.23123]
 [186.62459]
 [179.50404]
 [198.78612]
 [144.26987]]
step:  50 , cost:  7.2967253 , prediction:  [[146.24768]
 [186.61948]
 [179.50612]
 [198.78973]
 [144.25116]]
step:  60 , cost:  7.2351637 , prediction:  [[146.26407]
 [186.6144 ]
 [179.50821]
 [198.79332]
 [144.23254]]
step:  70 , cost:  7.1740828 , prediction:  [[146.28038]
 [186.6093 ]
 [179.51028]
 [198.79689]
 [144.21399]]
step:  80 , cost:  7.1135435 , prediction:  [[146.29662]
 [186.60425]
 [179.51234]
 [198.80045]
 [144.19551]]
step:  9

step:  870 , cost:  3.6518683 , prediction:  [[147.38307]
 [186.26598]
 [179.65018]
 [199.03816]
 [142.95987]]
step:  880 , cost:  3.6213307 , prediction:  [[147.3946 ]
 [186.26239]
 [179.65166]
 [199.04068]
 [142.94675]]
step:  890 , cost:  3.5910783 , prediction:  [[147.4061 ]
 [186.25882]
 [179.6531 ]
 [199.04318]
 [142.9337 ]]
step:  900 , cost:  3.561046 , prediction:  [[147.41754]
 [186.25525]
 [179.65454]
 [199.04567]
 [142.92068]]
step:  910 , cost:  3.531276 , prediction:  [[147.42892]
 [186.2517 ]
 [179.65599]
 [199.04817]
 [142.90773]]
step:  920 , cost:  3.5017953 , prediction:  [[147.44026]
 [186.24815]
 [179.65742]
 [199.05063]
 [142.89485]]
step:  930 , cost:  3.4725418 , prediction:  [[147.45155]
 [186.24464]
 [179.65887]
 [199.05312]
 [142.88202]]
step:  940 , cost:  3.4435127 , prediction:  [[147.46281]
 [186.24113]
 [179.6603 ]
 [199.05557]
 [142.86923]]
step:  950 , cost:  3.4147675 , prediction:  [[147.474  ]
 [186.23766]
 [179.66173]
 [199.05803]
 [142.8565 ]]
ste

step:  1710 , cost:  1.814547 , prediction:  [[148.19911]
 [186.0115 ]
 [179.75389]
 [199.21625]
 [142.03262]]
step:  1720 , cost:  1.7996514 , prediction:  [[148.20718]
 [186.00899]
 [179.75491]
 [199.218  ]
 [142.02347]]
step:  1730 , cost:  1.7848995 , prediction:  [[148.21521]
 [186.0065 ]
 [179.75595]
 [199.21976]
 [142.01436]]
step:  1740 , cost:  1.7702707 , prediction:  [[148.2232 ]
 [186.00401]
 [179.75697]
 [199.22151]
 [142.0053 ]]
step:  1750 , cost:  1.7557602 , prediction:  [[148.23116]
 [186.00153]
 [179.75798]
 [199.22324]
 [141.99625]]
step:  1760 , cost:  1.7413814 , prediction:  [[148.23907]
 [185.99905]
 [179.759  ]
 [199.22498]
 [141.98726]]
step:  1770 , cost:  1.7271221 , prediction:  [[148.24696]
 [185.99658]
 [179.76   ]
 [199.22668]
 [141.9783 ]]
step:  1780 , cost:  1.7129875 , prediction:  [[148.25484]
 [185.99416]
 [179.761  ]
 [199.2284 ]
 [141.96939]]
step:  1790 , cost:  1.6989673 , prediction:  [[148.26263]
 [185.9917 ]
 [179.762  ]
 [199.2301 ]
 [141.9

예제 1

In [16]:
testscore = np.loadtxt("data/test-score.csv", delimiter=",")
testscore

array([[ 80.,  79.,  77., 149.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]])

xdata: 1~3열, ydata: 4열

100, 70, 102 => 예상

60, 70, 100 => 예상

80, 90, 95 => 예상

cost 출력

In [17]:
xdata = testscore[:, :3]
ydata = testscore[:, 3].reshape(-1,1)
print(xdata)
print(ydata)
print(np.shape(xdata))
print(np.shape(ydata))

[[ 80.  79.  77.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]]
[[149.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]
(25, 3)
(25, 1)


In [18]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [19]:
hf = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-5).minimize(cost)

In [20]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [21]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    if step % 10 == 0:
        print("step: ", step, ", cost: ", cv, ", prediction: ", hv)
print("cost: ", cv)

step:  0 , cost:  238517.02 , prediction:  [[-322.09494]
 [-367.13562]
 [-364.15594]
 [-392.44846]
 [-282.32602]
 [-201.0498 ]
 [-288.50436]
 [-206.7028 ]
 [-337.01453]
 [-302.47772]
 [-281.04816]
 [-273.72476]
 [-380.4761 ]
 [-321.9297 ]
 [-288.76703]
 [-368.93475]
 [-310.41776]
 [-344.62894]
 [-363.99066]
 [-325.29773]
 [-339.3319 ]
 [-340.5449 ]
 [-325.0381 ]
 [-321.10922]
 [-383.12817]]
step:  10 , cost:  44.83306 , prediction:  [[149.30495]
 [180.31784]
 [175.24664]
 [194.9886 ]
 [135.2138 ]
 [106.76773]
 [151.1858 ]
 [119.2182 ]
 [174.60944]
 [171.38342]
 [142.59195]
 [143.99957]
 [176.8155 ]
 [141.36365]
 [152.94658]
 [186.58667]
 [130.83244]
 [183.02782]
 [167.30534]
 [150.08034]
 [176.28304]
 [173.02522]
 [166.56175]
 [138.1415 ]
 [184.24628]]
step:  20 , cost:  33.60571 , prediction:  [[152.52534 ]
 [184.03635 ]
 [178.92253 ]
 [198.98077 ]
 [138.05362 ]
 [108.84171 ]
 [154.1635  ]
 [121.411545]
 [178.06602 ]
 [174.5585  ]
 [145.46587 ]
 [146.81956 ]
 [180.62425 ]
 [144.54434 

step:  360 , cost:  27.49127 , prediction:  [[153.05634]
 [183.9725 ]
 [179.23804]
 [198.97224]
 [138.12671]
 [108.27241]
 [153.82317]
 [120.71255]
 [177.4185 ]
 [173.11926]
 [145.29755]
 [146.2192 ]
 [181.29933]
 [145.56386]
 [155.45132]
 [190.01347]
 [135.05682]
 [186.12572]
 [171.74554]
 [154.06284]
 [179.40488]
 [176.1436 ]
 [169.70108]
 [142.63416]
 [188.31522]]
step:  370 , cost:  27.336687 , prediction:  [[153.07027]
 [183.9702 ]
 [179.24593]
 [198.97122]
 [138.12834]
 [108.25662]
 [153.81319]
 [120.69282]
 [177.40036]
 [173.07956]
 [145.29237]
 [146.20238]
 [181.31703]
 [145.5911 ]
 [155.43752]
 [190.00363]
 [135.08879]
 [186.1119 ]
 [171.76674]
 [154.08203]
 [179.394  ]
 [176.1332 ]
 [169.69499]
 [142.66974]
 [188.3202 ]]
step:  380 , cost:  27.183426 , prediction:  [[153.08415 ]
 [183.96788 ]
 [179.25378 ]
 [198.9702  ]
 [138.12999 ]
 [108.24092 ]
 [153.80325 ]
 [120.673164]
 [177.3823  ]
 [173.04004 ]
 [145.28725 ]
 [146.18564 ]
 [181.33464 ]
 [145.61823 ]
 [155.42377 ]
 [18

step:  730 , cost:  22.556086 , prediction:  [[153.53625 ]
 [183.89717 ]
 [179.50772 ]
 [198.9356  ]
 [138.18884 ]
 [107.736015]
 [153.47632 ]
 [120.02719 ]
 [176.80153 ]
 [171.76212 ]
 [145.11952 ]
 [145.6456  ]
 [181.90593 ]
 [146.49956 ]
 [154.97449 ]
 [189.67873 ]
 [136.15857 ]
 [185.64339 ]
 [172.47102 ]
 [154.71835 ]
 [179.02774 ]
 [175.78943 ]
 [169.48782 ]
 [143.85129 ]
 [188.48958 ]]
step:  740 , cost:  22.442852 , prediction:  [[153.54825 ]
 [183.8954  ]
 [179.5144  ]
 [198.93462 ]
 [138.19055 ]
 [107.722786]
 [153.46754 ]
 [120.00988 ]
 [176.78632 ]
 [171.72845 ]
 [145.11504 ]
 [145.6314  ]
 [181.921   ]
 [146.52287 ]
 [154.96251 ]
 [189.67046 ]
 [136.18611 ]
 [185.63112 ]
 [172.48903 ]
 [154.73459 ]
 [179.01822 ]
 [175.78067 ]
 [169.48238 ]
 [143.8815  ]
 [188.49399 ]]
step:  750 , cost:  22.330572 , prediction:  [[153.56021]
 [183.89365]
 [179.52106]
 [198.93365]
 [138.19228]
 [107.70964]
 [153.45882]
 [119.99264]
 [176.7712 ]
 [171.69496]
 [145.11061]
 [145.61726]
 [181.9

step:  1120 , cost:  18.773489 , prediction:  [[153.9703  ]
 [183.83797 ]
 [179.74748 ]
 [198.8995  ]
 [138.25671 ]
 [107.264824]
 [153.15576 ]
 [119.395004]
 [176.25961 ]
 [170.55531 ]
 [144.9577  ]
 [145.13763 ]
 [182.44908 ]
 [147.3407  ]
 [154.5402  ]
 [189.38428 ]
 [137.15593 ]
 [185.19415 ]
 [173.11787 ]
 [155.30046 ]
 [178.68164 ]
 [175.47745 ]
 [169.2876  ]
 [144.93578 ]
 [188.65192 ]]
step:  1130 , cost:  18.691805 , prediction:  [[153.98056 ]
 [183.83669 ]
 [179.7531  ]
 [198.8986  ]
 [138.25847 ]
 [107.25387 ]
 [153.14809 ]
 [119.379906]
 [176.24702 ]
 [170.52705 ]
 [144.95386 ]
 [145.12576 ]
 [182.46184 ]
 [147.3605  ]
 [154.5299  ]
 [189.37741 ]
 [137.17952 ]
 [185.18335 ]
 [173.13304 ]
 [155.31407 ]
 [178.67339 ]
 [175.47017 ]
 [169.28276 ]
 [144.9612  ]
 [188.6558  ]]
step:  1140 , cost:  18.610815 , prediction:  [[153.99077 ]
 [183.8354  ]
 [179.75867 ]
 [198.8977  ]
 [138.26021 ]
 [107.242966]
 [153.14044 ]
 [119.364845]
 [176.23447 ]
 [170.4989  ]
 [144.95003 ]
 [145.

step:  1530 , cost:  15.925088 , prediction:  [[154.35902]
 [183.79382]
 [179.95808]
 [198.8643 ]
 [138.32906]
 [106.85667]
 [152.86194]
 [118.81669]
 [175.79024]
 [169.495  ]
 [144.812  ]
 [144.69344]
 [182.93008]
 [148.08888]
 [154.14836]
 [189.1288 ]
 [138.05   ]
 [184.77902]
 [173.68793]
 [155.81114]
 [178.36676]
 [175.2063 ]
 [169.10104]
 [145.89082]
 [188.80188]]
step:  1540 , cost:  15.867029 , prediction:  [[154.36774 ]
 [183.79294 ]
 [179.96275 ]
 [198.86348 ]
 [138.33081 ]
 [106.847694]
 [152.85526 ]
 [118.80358 ]
 [175.7799  ]
 [169.47148 ]
 [144.8087  ]
 [144.68361 ]
 [182.9408  ]
 [148.10556 ]
 [154.13954 ]
 [189.12318 ]
 [138.07004 ]
 [184.76956 ]
 [173.70059 ]
 [155.82243 ]
 [178.35963 ]
 [175.20032 ]
 [169.09677 ]
 [145.912   ]
 [188.80528 ]]
step:  1550 , cost:  15.809458 , prediction:  [[154.3764  ]
 [183.79208 ]
 [179.96739 ]
 [198.86266 ]
 [138.33258 ]
 [106.838776]
 [152.84862 ]
 [118.79052 ]
 [175.76965 ]
 [169.4481  ]
 [144.80545 ]
 [144.67384 ]
 [182.95146 ]
 [1

step:  1920 , cost:  13.982178 , prediction:  [[154.67422 ]
 [183.76561 ]
 [180.12537 ]
 [198.83333 ]
 [138.39754 ]
 [106.537476]
 [152.6179  ]
 [118.33738 ]
 [175.42323 ]
 [168.6527  ]
 [144.69316 ]
 [144.34238 ]
 [183.3155  ]
 [148.6912  ]
 [153.82814 ]
 [188.92867 ]
 [138.7757  ]
 [184.4315  ]
 [174.14233 ]
 [156.21614 ]
 [178.10725 ]
 [174.9935  ]
 [168.94362 ]
 [146.65143 ]
 [188.92738 ]]
step:  1930 , cost:  13.9401455 , prediction:  [[154.68169 ]
 [183.76505 ]
 [180.12927 ]
 [198.83257 ]
 [138.3993  ]
 [106.530075]
 [152.61208 ]
 [118.32592 ]
 [175.41472 ]
 [168.63298 ]
 [144.69035 ]
 [144.3342  ]
 [183.32457 ]
 [148.70538 ]
 [153.82056 ]
 [188.92403 ]
 [138.79288 ]
 [184.42317 ]
 [174.15298 ]
 [156.22562 ]
 [178.10106 ]
 [174.98857 ]
 [168.93982 ]
 [146.66927 ]
 [188.9304  ]]
step:  1940 , cost:  13.898425 , prediction:  [[154.68912]
 [183.76448]
 [180.1332 ]
 [198.8318 ]
 [138.40105]
 [106.5227 ]
 [152.60625]
 [118.31448]
 [175.40627]
 [168.61336]
 [144.68755]
 [144.32605]
 [1

In [22]:
pred = np.array([[100, 70, 102], [60, 70, 100], [80, 90, 95]])
for data in pred:
    print(sess.run(hf, feed_dict={x:data.reshape(-1,3)}))

[[190.91832]]
[[187.12474]]
[[187.50401]]


### train_test_split

In [51]:
from sklearn.model_selection import train_test_split

In [52]:
x,y=np.arange(10).reshape((5,2)), range(5)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [53]:
list(y)

[0, 1, 2, 3, 4]

In [54]:
xtrain, xtest, ytrain, ytest=train_test_split(x,y, test_size=0.33, random_state=42)
print(xtrain)
print(xtest)

[[4 5]
 [0 1]
 [6 7]]
[[2 3]
 [8 9]]


### Scaling

In [55]:
x=np.array([[10., -10., 1],
          [5., 0., 2.],
           [15., 10., 22.]])
x

array([[ 10., -10.,   1.],
       [  5.,   0.,   2.],
       [ 15.,  10.,  22.]])

In [58]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit_transform(x)
scaler.transform(x)

array([[0.5       , 0.        , 0.        ],
       [0.        , 0.5       , 0.04761905],
       [1.        , 1.        , 1.        ]])

예제 2

In [23]:
stock = pd.read_csv("data/GOOG.csv")
stock = stock.iloc[:, [1, 2, 3, 4, 6]]

In [24]:
stock

Open         High          Low        Close   Volume
0    1228.010010  1234.916016  1211.469971  1219.739990  1849900
1    1220.010010  1227.588013  1205.599976  1217.260010  1644700
2    1228.000000  1233.469971  1210.209961  1220.010010  1567200
3    1205.900024  1229.880005  1204.790039  1226.150024  1531300
4    1229.619995  1230.000000  1215.060059  1223.709961  1089600
5    1225.000000  1226.088013  1215.796997  1224.770020  1081700
6    1237.000000  1251.170044  1236.170044  1242.219971  1494000
7    1240.469971  1256.500000  1238.008057  1245.609985  1370300
8    1249.900024  1255.541992  1246.010010  1249.099976   848600
9    1243.000000  1245.694946  1232.000000  1237.609985  1108700
10   1236.979980  1249.272949  1233.640991  1235.010010   997300
11   1235.189941  1245.869995  1225.109985  1242.099976  1348100
12   1229.260010  1235.239990  1209.510010  1214.380005  1828800
13   1224.729980  1226.000000  1202.550049  1206.489990  1343200
14   1202.030029  1209.020020  1188.239990  1200.959961  1389600
15   1205.020020  1211.000000  1194.625977  1207.770020   870800
16   1208.000000  1217.260010  1200.354004  1201.619995  1205600
17   1200.000000  1211.839966  1199.000000  1207.329956   887400
18   1207.140015  1221.280029  1204.239990  1205.380005   992600
19   1208.819946  1221.650024  1206.359009  1220.650024   946600
20   1227.599976  1243.089966  1225.715942  1241.819946  1156300
21   1241.290039  1242.545044  1228.689941  1231.150024  1304000
22   1237.449951  1250.660034  1236.359009  1249.300049  1298900
23   1244.229980  1253.635010  1232.589966  1239.119995  1331400
24   1234.979980  1238.660034  1211.285034  1218.189941  1816400
25   1204.270020  1212.989990  1192.500000  1197.000000  1831000
26   1193.800049  1199.010010  1162.000000  1186.479980  2061300
27   1186.300049  1186.300049  1152.000000  1171.439941  1888500
28   1158.670044  1175.260010  1157.214966  1164.829956  1401300
29   1172.189941  1174.540039  1160.109985  1164.640015  1115400
..           ...          ...          ...          ...      ...
221  1086.280029  1099.180054  1086.280029  1092.500000   941600
222  1109.689941  1116.390015  1098.989990  1103.599976  1386700
223  1105.599976  1107.000000  1093.479980  1102.329956  1338800
224  1119.989990  1120.119995  1104.739990  1111.420044  1262000
225  1109.239990  1124.109985  1108.079956  1121.880005  1947600
226  1119.609985  1122.000000  1111.010010  1115.520020  1395600
227  1112.660034  1114.349976  1083.800049  1086.349976  1546900
228  1086.500000  1092.969971  1072.239990  1079.800049  1810900
229  1084.000000  1087.099976  1075.290039  1076.010010  1004300
230  1076.390015  1081.000000  1073.369995  1080.910034  1693200
231  1098.000000  1107.579956  1093.703003  1097.949951  1436300
232  1102.239990  1111.770020  1098.170044  1111.250000   991600
233  1117.410034  1126.760010  1113.859985  1121.579956   767000
234  1117.800049  1132.880005  1116.140015  1131.589966  1264300
235  1125.170044  1125.979980  1111.209961  1116.349976  1236400
236  1111.800049  1128.025024  1107.170044  1124.829956  1330400
237  1131.219971  1142.050049  1130.969971  1140.479980  1209500
238  1143.250000  1153.069946  1139.579956  1144.209961  1195500
239  1143.989990  1147.339966  1138.780029  1144.900024   864000
240  1146.859985  1150.819946  1139.400024  1150.339966   903800
241  1146.000000  1158.579956  1145.000000  1153.579956  1238800
242  1150.969971  1158.359985  1145.770020  1146.349976  1170000
243  1141.739990  1147.604980  1132.729980  1146.329956  1291300
244  1148.189941  1151.140015  1129.619995  1130.099976  1647200
245  1133.449951  1139.250000  1124.239990  1138.069946  1301500
246  1144.000000  1146.900024  1131.800049  1146.209961  1093700
247  1131.900024  1144.000000  1126.989990  1137.810059  1589800
248  1137.819946  1141.699951  1120.920044  1132.119995  2209800
249  1224.040039  1265.550049  1224.000000  1250.410034  4805800
250  1241.050049  1247.369995  1228.229980  123

예제 2-1. Volume 예측

In [25]:
xdata = np.array(stock.iloc[:, :4])
ydata = np.array(stock.iloc[:, 4]).reshape(-1,1)
print(xdata.shape)
print(ydata.shape)

(251, 4)
(251, 1)


In [26]:
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([4, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [27]:
hf = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-7).minimize(cost)

In [28]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [29]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    if step % 10 == 0:
        print("step: ", step, ", cost: ", cv)
print("prediction: ", hv)

step:  0 , cost:  3103257800000.0
step:  10 , cost:  577670700000.0
step:  20 , cost:  577595100000.0
step:  30 , cost:  577519500000.0
step:  40 , cost:  577444000000.0
step:  50 , cost:  577368360000.0
step:  60 , cost:  577293000000.0
step:  70 , cost:  577217400000.0
step:  80 , cost:  577142060000.0
step:  90 , cost:  577066570000.0
step:  100 , cost:  576991130000.0
step:  110 , cost:  576915800000.0
step:  120 , cost:  576840400000.0
step:  130 , cost:  576765030000.0
step:  140 , cost:  576689730000.0
step:  150 , cost:  576614500000.0
step:  160 , cost:  576539200000.0
step:  170 , cost:  576463960000.0
step:  180 , cost:  576388700000.0
step:  190 , cost:  576313560000.0
step:  200 , cost:  576238400000.0
step:  210 , cost:  576163200000.0
step:  220 , cost:  576088100000.0
step:  230 , cost:  576013000000.0
step:  240 , cost:  575937900000.0
step:  250 , cost:  575862900000.0
step:  260 , cost:  575787800000.0
step:  270 , cost:  575712850000.0
step:  280 , cost:  5756379000

예제 2-2. Close 예측

In [30]:
xdata = np.array(stock.iloc[:, [0, 1, 2, 4]])
ydata = np.array(stock.iloc[:, 3]).reshape(-1,1)
print(xdata.shape)
print(ydata.shape)

(251, 4)
(251, 1)


In [31]:
x = tf.placeholder(tf.float32, shape=[None, 4])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([4, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hf = tf.matmul(x, w) + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-15).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [32]:
for step in range(2001):
    cv, hv, _ = sess.run([cost, hf, train], feed_dict={x:xdata, y:ydata})
    if step % 10 == 0:
        print("step: ", step, ", cost: ", cv)
print("prediction: ", hv)

step:  0 , cost:  1104629300000.0
step:  10 , cost:  974974000000.0
step:  20 , cost:  860537100000.0
step:  30 , cost:  759532600000.0
step:  40 , cost:  670383200000.0
step:  50 , cost:  591697700000.0
step:  60 , cost:  522247800000.0
step:  70 , cost:  460949500000.0
step:  80 , cost:  406845980000.0
step:  90 , cost:  359092800000.0
step:  100 , cost:  316944740000.0
step:  110 , cost:  279743730000.0
step:  120 , cost:  246909200000.0
step:  130 , cost:  217928580000.0
step:  140 , cost:  192349590000.0
step:  150 , cost:  169772830000.0
step:  160 , cost:  149846000000.0
step:  170 , cost:  132258090000.0
step:  180 , cost:  116734575000.0
step:  190 , cost:  103033140000.0
step:  200 , cost:  90939830000.0
step:  210 , cost:  80266000000.0
step:  220 , cost:  70845006000.0
step:  230 , cost:  62529800000.0
step:  240 , cost:  55190600000.0
step:  250 , cost:  48712810000.0
step:  260 , cost:  42995347000.0
step:  270 , cost:  37948977000.0
step:  280 , cost:  33494910000.0
step

예제 2-3. 오늘 Close 예측

# Queue Runner

In [33]:
QUEUE_LENGTH = 20

# 큐 생성
q = tf.FIFOQueue(QUEUE_LENGTH, "float")

# 큐 러너 생성
enq_ops = q.enqueue_many(([1.0, 2.0, 3.0, 4.0],))
qr = tf.train.QueueRunner(q, [enq_ops, enq_ops, enq_ops])

W0730 15:09:38.818945  2376 deprecation.py:323] From <ipython-input-33-fc2a2a2e0262>:8: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [34]:
sess = tf.Session()
coord = tf.train.Coordinator()
threads = qr.create_threads(sess, coord=coord, start=True)

for step in range(10):
    print(sess.run(q.dequeue()))
    
coord.request_stop()    # 스레드 정지
coord.join(threads)    # 정지될 때까지 기다리는 함수

1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
1.0
2.0


예제

In [35]:
QUEUE_LENGTH = 20
q = tf.FIFOQueue(QUEUE_LENGTH, "float")
enq_ops1 = q.enqueue_many(([1.0, 2.0, 3.0, 4.0],))
enq_ops2 = q.enqueue_many(([5.0, 6.0, 7.0, 8.0],))
enq_ops3 = q.enqueue_many(([9.0, 10.0, 11.0, 12.0],))
qr = tf.train.QueueRunner(q, [enq_ops1, enq_ops2, enq_ops3])

In [36]:
sess = tf.Session()
coord = tf.train.Coordinator()
threads = qr.create_threads(sess, coord=coord, start=True)

for step in range(30):
    print(sess.run(q.dequeue()))
    
coord.request_stop()
coord.join(threads)

1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
1.0
2.0
3.0
4.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0
11.0
12.0
1.0
2.0
3.0
4.0
5.0
6.0


파일에서 데이터 읽기 작업 순서
1. 파일 목록 읽기
2. 파일 목록을 파일이름큐에 저장
3. reader가 파일이름큐에서 파일명을 하나씩 읽어온다
4. decoder는 파일에 있는 데이터를 읽어들인다
5. 데이터를 정제(전처리)한다
6. 정제된 데이터를 example queue에 저장
7. 학습 진행

In [37]:
queue = tf.train.string_input_producer(["q_1.txt", "q_2.txt", "q_3.txt"], shuffle=False)
coord = tf.train.Coordinator()

W0730 15:09:39.662496  2376 deprecation.py:323] From <ipython-input-37-51accf5756e0>:1: string_input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(string_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0730 15:09:39.662496  2376 deprecation.py:323] From C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\training\input.py:278: input_producer (from tensorflow.python.training.input) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.Dataset.from_tensor_slices(input_tensor).shuffle(tf.shape(input_tensor, out_type=tf.int64)[0]).repeat(num_epochs)`. If `shuffle=False`, omit the `.shuffle(...)`.
W0730 15:09:39.662496 

In [ ]:
reader = tf.TextLineReader()
key, value = reader.read(queue=queue)
print(sess.run(key))
print(sess.run(value))

W0730 15:05:52.369323  7976 deprecation.py:323] From <ipython-input-38-314454343076>:1: TextLineReader.__init__ (from tensorflow.python.ops.io_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Queue-based input pipelines have been replaced by `tf.data`. Use `tf.data.TextLineDataset`.


In [ ]:
for i in range(100):
    speed, distance = tf.decode_csv(value, record_defaults=[[0], [0]])
    print(sess.run([speed, distance]))
coord.request_stop()
coord.join(threads)

# 연습문제 1

sqft_living에 따른 price?

(데이터(8:2) 분리)

In [41]:
house = pd.read_csv("data/house2/train.csv")
house

id             date      price  bedrooms  bathrooms  sqft_living  \
0          0  20141013T000000   221900.0         3       1.00         1180   
1          1  20150225T000000   180000.0         2       1.00          770   
2          2  20150218T000000   510000.0         3       2.00         1680   
3          3  20140627T000000   257500.0         3       2.25         1715   
4          4  20150115T000000   291850.0         3       1.50         1060   
5          5  20150403T000000   662500.0         3       2.50         3560   
6          6  20140527T000000   468000.0         2       1.00         1160   
7          7  20140528T000000   310000.0         3       1.00         1430   
8          8  20141007T000000   400000.0         3       1.75         1370   
9          9  20150312T000000   530000.0         5       2.00         1810   
10        10  20150124T000000   650000.0         4       3.00         2950   
11        11  20140731T000000   395000.0         3       2.00         1890   
12        12  20140529T000000   485000.0         4       1.00         1600   
13        13  20141205T000000   189000.0         2       1.00         1200   
14        14  20150424T000000   230000.0         3       1.00         1250   
15        15  20140514T000000   385000.0         4       1.75         1620   
16        16  20140826T000000  2000000.0         3       2.75         3050   
17        17  20140516T000000   252700.0         2       1.50         1070   
18        18  20141120T000000   329000.0         3       2.25         2450   
19        19  20141103T000000   233000.0         3       2.00         1710   
20        20  20140626T000000   937000.0         3       1.75         2450   
21        21  20141201T000000   667000.0         3       1.00         1400   
22        22  20141110T000000   580500.0         3       2.50         2320   
23        23  20140624T000000   687500.0         4       1.75         2330   
24        24  20141110T000000   535000.0         3       1.00         1090   
25        25  20141203T000000   322500.0         4       2.75         2060   
26        26  20140613T000000   696000.0         3       2.50         2300   
27        27  20141230T000000   640000.0         4       2.00         2360   
28        28  20150213T000000   240000.0         4       1.00         1220   
29        29  20140620T000000   605000.0         4       2.50         2620   
...      ...              ...        ...       ...        ...          ...   
15005  15005  20140513T000000   330000.0         3       2.50         1450   
15006  15006  20150502T000000   608500.0         4       3.50         2850   
15007  15007  20140520T000000   785000.0         4       3.50         3070   
15008  15008  20140507T000000   610950.0         3       3.00         1680   
15009  15009  20141111T000000   399950.0         3       2.50         3087   
15010  15010  20150123T000000   579000.0         4       3.25         1900   
15011  15011  20140623T000000   362500.0         2       1.50          940   
15012  15012  20140529T000000   645000.0         3       3.25         1730   
15013  15013  20141003T000000   594866.0         3       3.00         2780   
15014  15014  20141112T000000   490000.0         3       2.25         1500   
15015  15015  20140610T000000   399950.0         2       1.00          710   
15016  15016  20140828T000000   270000.0         3       2.50         1870   
15017  15017  20141015T000000   505000.0         2       2.50         1430   
15018  15018  20150305T000000   385000.0         3       2.50         1520   
15019  15019  20141113T000000   414500.0         2       1.50         1210   
15020  15020  20140910T000000   347500.0         3       2.50         2540   
15021  15021  20140514T000000  1222500.0         4       3.50         4910   
15022  15022  20150317T000000  1088000.0         5       3.75         4170   
15023  15023  20141017T000000   350000.0         4       2.75         2500   
15024  15024  20140813T000000   

In [43]:
house1 = house[["price", "sqft_living"]]
house1

price  sqft_living
0       221900.0         1180
1       180000.0          770
2       510000.0         1680
3       257500.0         1715
4       291850.0         1060
5       662500.0         3560
6       468000.0         1160
7       310000.0         1430
8       400000.0         1370
9       530000.0         1810
10      650000.0         2950
11      395000.0         1890
12      485000.0         1600
13      189000.0         1200
14      230000.0         1250
15      385000.0         1620
16     2000000.0         3050
17      252700.0         1070
18      329000.0         2450
19      233000.0         1710
20      937000.0         2450
21      667000.0         1400
22      580500.0         2320
23      687500.0         2330
24      535000.0         1090
25      322500.0         2060
26      696000.0         2300
27      640000.0         2360
28      240000.0         1220
29      605000.0         2620
...          ...          ...
15005   330000.0         1450
15006   608500.0         2850
15007   785000.0         3070
15008   610950.0         1680
15009   399950.0         3087
15010   579000.0         1900
15011   362500.0          940
15012   645000.0         1730
15013   594866.0         2780
15014   490000.0         1500
15015   399950.0          710
15016   270000.0         1870
15017   505000.0         1430
15018   385000.0         1520
15019   414500.0         1210
15020   347500.0         2540
15021  1222500.0         4910
15022  1088000.0         4170
15023   350000.0         2500
15024   679950.0         3600
15025  1575000.0         3410
15026   810000.0         3990
15027  1537000.0         4470
15028   467000.0         1425
15029   507250.0         2270
15030   610685.0         2520
15031  1007500.0         3510
15032   360000.0         1530
15033   400000.0         2310
15034   325000.0         1020

[15035 rows x 2 columns]

In [110]:
xdata = list(house1["sqft_living"])
ydata = list(house1["price"])

In [111]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.2, random_state=42)

In [112]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
w = tf.Variable(tf.random_normal([1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

In [113]:
hf = x * w + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-7).minimize(cost)

In [114]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [115]:
for step in range(2001):
    sess.run(train, feed_dict={x:xtrain, y:ytrain})
    if step % 20 == 0:
        wv, cv, hv = sess.run([w, cost, hf], feed_dict={x:xtrain, y:ytrain})
        print("step: %s, w: %s, cost: %s, prediction: %s" % (step, wv, cv, hv))

step: 0, w: [274.11264], cost: 71703765000.0, prediction: [282335.34 287817.6  720915.56 ... 877159.75 337157.88 465990.8 ]
step: 20, w: [263.53705], cost: 71121986000.0, prediction: [271442.44 276713.2  693101.7  ... 843317.8  324149.84 448012.25]
step: 40, w: [263.53705], cost: 71121986000.0, prediction: [271442.38 276713.12 693101.7  ... 843317.8  324149.78 448012.2 ]
step: 60, w: [263.53708], cost: 71121986000.0, prediction: [271442.38 276713.12 693101.7  ... 843317.8  324149.78 448012.22]
step: 80, w: [263.53708], cost: 71121986000.0, prediction: [271442.34 276713.1  693101.7  ... 843317.8  324149.75 448012.2 ]
step: 100, w: [263.5371], cost: 71121986000.0, prediction: [271442.34 276713.1  693101.75 ... 843317.9  324149.78 448012.22]
step: 120, w: [263.5371], cost: 71121986000.0, prediction: [271442.3  276713.06 693101.7  ... 843317.8  324149.75 448012.2 ]
step: 140, w: [263.53714], cost: 71121986000.0, prediction: [271442.3  276713.06 693101.75 ... 843317.94 324149.75 448012.2 ]


step: 1360, w: [263.538], cost: 71121940000.0, prediction: [271441.03 276711.8  693101.8  ... 843318.44 324148.62 448011.5 ]
step: 1380, w: [263.538], cost: 71121945000.0, prediction: [271441.   276711.78 693101.8  ... 843318.44 324148.6  448011.47]
step: 1400, w: [263.53802], cost: 71121940000.0, prediction: [271441.   276711.78 693101.8  ... 843318.5  324148.62 448011.5 ]
step: 1420, w: [263.53802], cost: 71121940000.0, prediction: [271440.97 276711.75 693101.8  ... 843318.5  324148.6  448011.47]
step: 1440, w: [263.53806], cost: 71121940000.0, prediction: [271440.94 276711.72 693101.8  ... 843318.5  324148.56 448011.44]
step: 1460, w: [263.53806], cost: 71121940000.0, prediction: [271440.9  276711.7  693101.8  ... 843318.5  324148.53 448011.4 ]
step: 1480, w: [263.5381], cost: 71121940000.0, prediction: [271440.9  276711.7  693101.9  ... 843318.56 324148.53 448011.44]
step: 1500, w: [263.5381], cost: 71121940000.0, prediction: [271440.88 276711.66 693101.8  ... 843318.5  324148.5  4

In [116]:
hvList = sess.run(hf, feed_dict={x:xtest})

In [117]:
comparison = pd.DataFrame({
    "prediction": hvList,
    "ytest": ytest
})
comparison

prediction      ytest
0     3.900327e+05   256000.0
1     5.059896e+05   235000.0
2     3.715850e+05   626700.0
3     2.081911e+05   245500.0
4     5.613326e+05   593450.0
5     3.979388e+05   400000.0
6     4.163865e+05   320000.0
7     5.534265e+05   465000.0
8     5.033542e+05   323000.0
9     5.455204e+05   250000.0
10    6.430296e+05   925000.0
11    3.452312e+05   575000.0
12    3.531373e+05   425000.0
13    6.641126e+05   770000.0
14    2.819819e+05   200000.0
15    4.743650e+05   495000.0
16    5.955926e+05   864000.0
17    5.876865e+05   482000.0
18    4.585527e+05   568000.0
19    2.767112e+05   439000.0
20    7.853403e+05   610000.0
21    5.481558e+05   601000.0
22    5.007188e+05   340000.0
23    3.478665e+05   529000.0
24    6.772896e+05   654000.0
25    3.109712e+05   425000.0
26    8.986619e+05  1575000.0
27    6.114049e+05   423000.0
28    3.399604e+05   315000.0
29    4.822712e+05   360000.0
...            ...        ...
2977  9.381926e+05   486000.0
2978  6.008634e+05   380000.0
2979  8.512249e+05   765000.0
2980  5.297081e+05   490000.0
2981  2.793465e+05   254000.0
2982  4.348342e+05   327500.0
2983  6.456649e+05   969000.0
2984  4.269281e+05   260656.0
2985  3.715850e+05   658500.0
2986  6.667481e+05   880000.0
2987  9.935357e+05  1229000.0
2988  4.295635e+05   360000.0
2989  7.695280e+05   859000.0
2990  4.058450e+05   441000.0
2991  6.509358e+05   430000.0
2992  3.478665e+05   420200.0
2993  5.218019e+05   564000.0
2994  4.242927e+05   393000.0
2995  6.193111e+05   875000.0
2996  5.481558e+05   520000.0
2997  3.715850e+05   335000.0
2998  1.228085e+06  2641100.0
2999  4.559173e+05   265000.0
3000  2.503573e+05   304000.0
3001  4.321988e+05   478000.0
3002  4.321988e+05   640500.0
3003  5.955926e+05   795000.0
3004  3.320542e+05   353000.0
3005  4.901773e+05   560000.0
3006  3.346896e+05   510500.0

[3007 rows x 2 columns]

# 연습문제 2

sqft_living, bedrooms, bathrooms에 따른 price?

(데이터(8:2) 분리)

In [120]:
house2 = house[["price", "sqft_living", "bedrooms", "bathrooms"]]
house2

price  sqft_living  bedrooms  bathrooms
0       221900.0         1180         3       1.00
1       180000.0          770         2       1.00
2       510000.0         1680         3       2.00
3       257500.0         1715         3       2.25
4       291850.0         1060         3       1.50
5       662500.0         3560         3       2.50
6       468000.0         1160         2       1.00
7       310000.0         1430         3       1.00
8       400000.0         1370         3       1.75
9       530000.0         1810         5       2.00
10      650000.0         2950         4       3.00
11      395000.0         1890         3       2.00
12      485000.0         1600         4       1.00
13      189000.0         1200         2       1.00
14      230000.0         1250         3       1.00
15      385000.0         1620         4       1.75
16     2000000.0         3050         3       2.75
17      252700.0         1070         2       1.50
18      329000.0         2450         3       2.25
19      233000.0         1710         3       2.00
20      937000.0         2450         3       1.75
21      667000.0         1400         3       1.00
22      580500.0         2320         3       2.50
23      687500.0         2330         4       1.75
24      535000.0         1090         3       1.00
25      322500.0         2060         4       2.75
26      696000.0         2300         3       2.50
27      640000.0         2360         4       2.00
28      240000.0         1220         4       1.00
29      605000.0         2620         4       2.50
...          ...          ...       ...        ...
15005   330000.0         1450         3       2.50
15006   608500.0         2850         4       3.50
15007   785000.0         3070         4       3.50
15008   610950.0         1680         3       3.00
15009   399950.0         3087         3       2.50
15010   579000.0         1900         4       3.25
15011   362500.0          940         2       1.50
15012   645000.0         1730         3       3.25
15013   594866.0         2780         3       3.00
15014   490000.0         1500         3       2.25
15015   399950.0          710         2       1.00
15016   270000.0         1870         3       2.50
15017   505000.0         1430         2       2.50
15018   385000.0         1520         3       2.50
15019   414500.0         1210         2       1.50
15020   347500.0         2540         3       2.50
15021  1222500.0         4910         4       3.50
15022  1088000.0         4170         5       3.75
15023   350000.0         2500         4       2.75
15024   679950.0         3600         5       2.75
15025  1575000.0         3410         4       3.25
15026   810000.0         3990         4       3.00
15027  1537000.0         4470         5       3.75
15028   467000.0         1425         3       2.50
15029   507250.0         2270         3       2.50
15030   610685.0         2520         4       2.50
15031  1007500.0         3510         4       3.50
15032   360000.0         1530         3       2.50
15033   400000.0         2310         4       2.50
15034   325000.0         1020         2       0.75

[15035 rows x 4 columns]

In [125]:
xdata = np.array(house2[["sqft_living", "bedrooms", "bathrooms"]])
ydata = np.array(house2[["price"]])
print(xdata.shape)
print(ydata.shape)

(15035, 3)
(15035, 1)


In [126]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.2, random_state=42)

In [138]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hf = x @ w + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-7).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [139]:
for step in range(2001):
    sess.run(train, feed_dict={x:xtrain, y:ytrain})
    if step % 20 == 0:
        wv, cv, hv = sess.run([w, cost, hf], feed_dict={x:xtrain, y:ytrain})
        print("step: %s, w: %s, cost: %s, prediction: %s" % (step, wv, cv, hv))

step: 0, w: [[274.1338   ]
 [  2.3777287]
 [ -0.822227 ]], cost: 71706714000.0, prediction: [[282362.28]
 [287843.7 ]
 [720980.5 ]
 ...
 [877236.1 ]
 [337189.03]
 [466033.03]]
step: 20, w: [[263.53424  ]
 [  2.1552057]
 [ -0.8670596]], cost: 71122215000.0, prediction: [[271444.22]
 [276713.6 ]
 [693102.7 ]
 ...
 [843316.5 ]
 [324151.06]
 [448013.03]]
step: 40, w: [[263.5346    ]
 [  1.9480138 ]
 [ -0.90180194]], cost: 71122180000.0, prediction: [[271444.12]
 [276713.47]
 [693102.7 ]
 ...
 [843316.75]
 [324151.03]
 [448012.9 ]]
step: 60, w: [[263.53494  ]
 [  1.7408228]
 [ -0.9365436]], cost: 71122170000.0, prediction: [[271443.97]
 [276713.25]
 [693102.6 ]
 ...
 [843316.9 ]
 [324150.94]
 [448012.72]]
step: 80, w: [[263.53528   ]
 [  1.5336325 ]
 [ -0.97128475]], cost: 71122140000.0, prediction: [[271443.84]
 [276713.06]
 [693102.6 ]
 ...
 [843316.94]
 [324150.9 ]
 [448012.53]]
step: 100, w: [[263.5356   ]
 [  1.3264437]
 [ -1.0060257]], cost: 71122125000.0, prediction: [[271443.72]
 [2

 [448004.22]]
step: 1180, w: [[263.55435  ]
 [ -9.860041 ]
 [ -2.8815186]], cost: 71120890000.0, prediction: [[271436.84]
 [276703.6 ]
 [693101.9 ]
 ...
 [843325.75]
 [324147.72]
 [448004.06]]
step: 1200, w: [[263.55472 ]
 [-10.06716 ]
 [ -2.916242]], cost: 71120860000.0, prediction: [[271436.75]
 [276703.47]
 [693102.  ]
 ...
 [843326.  ]
 [324147.7 ]
 [448003.97]]
step: 1220, w: [[263.55505  ]
 [-10.274279 ]
 [ -2.9509652]], cost: 71120850000.0, prediction: [[271436.6 ]
 [276703.25]
 [693101.9 ]
 ...
 [843326.06]
 [324147.6 ]
 [448003.78]]
step: 1240, w: [[263.5554   ]
 [-10.481398 ]
 [ -2.9856877]], cost: 71120820000.0, prediction: [[271436.44]
 [276703.06]
 [693101.9 ]
 ...
 [843326.25]
 [324147.5 ]
 [448003.6 ]]
step: 1260, w: [[263.55576  ]
 [-10.688517 ]
 [ -3.0204082]], cost: 71120810000.0, prediction: [[271436.34]
 [276702.9 ]
 [693101.9 ]
 ...
 [843326.44]
 [324147.5 ]
 [448003.47]]
step: 1280, w: [[263.5561   ]
 [-10.895636 ]
 [ -3.0551267]], cost: 71120790000.0, prediction:

In [140]:
hvs = sess.run(hf, feed_dict={x:xtest})

In [149]:
hvs = hvs.reshape(-1)
ytest = ytest.reshape(-1)

In [150]:
comparison = pd.DataFrame({
    "prediction": list(hvs),
    "ytest": list(ytest)
})
comparison

prediction      ytest
0     3.900127e+05   256000.0
1     5.059688e+05   235000.0
2     3.715672e+05   626700.0
3     2.081752e+05   245500.0
4     5.613150e+05   593450.0
5     3.979229e+05   400000.0
6     4.163706e+05   320000.0
7     5.534079e+05   465000.0
8     5.033504e+05   323000.0
9     5.455181e+05   250000.0
10    6.430385e+05   925000.0
11    3.452492e+05   575000.0
12    3.530753e+05   425000.0
13    6.641089e+05   770000.0
14    2.819377e+05   200000.0
15    4.743546e+05   495000.0
16    5.955811e+05   864000.0
17    5.876535e+05   482000.0
18    4.585405e+05   568000.0
19    2.767030e+05   439000.0
20    7.853472e+05   610000.0
21    5.481355e+05   601000.0
22    5.007125e+05   340000.0
23    3.478601e+05   529000.0
24    6.773024e+05   654000.0
25    3.109442e+05   425000.0
26    8.986784e+05  1575000.0
27    6.113919e+05   423000.0
28    3.399541e+05   315000.0
29    4.822649e+05   360000.0
...            ...        ...
2977  9.382170e+05   486000.0
2978  6.008676e+05   380000.0
2979  8.512394e+05   765000.0
2980  5.297040e+05   490000.0
2981  2.793387e+05   254000.0
2982  4.348042e+05   327500.0
2983  6.456580e+05   969000.0
2984  4.269187e+05   260656.0
2985  3.715877e+05   658500.0
2986  6.667435e+05   880000.0
2987  9.935621e+05  1229000.0
2988  4.295318e+05   360000.0
2989  7.695514e+05   859000.0
2990  4.058311e+05   441000.0
2991  6.509262e+05   430000.0
2992  3.478449e+05   420200.0
2993  5.218002e+05   564000.0
2994  4.242431e+05   393000.0
2995  6.193194e+05   875000.0
2996  5.481419e+05   520000.0
2997  3.715650e+05   335000.0
2998  1.228116e+06  2641100.0
2999  4.558843e+05   265000.0
3000  2.503440e+05   304000.0
3001  4.321847e+05   478000.0
3002  4.322052e+05   640500.0
3003  5.955929e+05   795000.0
3004  3.320308e+05   353000.0
3005  4.901708e+05   560000.0
3006  3.346697e+05   510500.0

[3007 rows x 2 columns]

# 연습문제 2-2 (MinMaxScaler 사용)

sqft_living, bedrooms, bathrooms에 따른 price?

(데이터(8:2) 분리)

In [151]:
house2 = house[["price", "sqft_living", "bedrooms", "bathrooms"]]
house2

price  sqft_living  bedrooms  bathrooms
0       221900.0         1180         3       1.00
1       180000.0          770         2       1.00
2       510000.0         1680         3       2.00
3       257500.0         1715         3       2.25
4       291850.0         1060         3       1.50
5       662500.0         3560         3       2.50
6       468000.0         1160         2       1.00
7       310000.0         1430         3       1.00
8       400000.0         1370         3       1.75
9       530000.0         1810         5       2.00
10      650000.0         2950         4       3.00
11      395000.0         1890         3       2.00
12      485000.0         1600         4       1.00
13      189000.0         1200         2       1.00
14      230000.0         1250         3       1.00
15      385000.0         1620         4       1.75
16     2000000.0         3050         3       2.75
17      252700.0         1070         2       1.50
18      329000.0         2450         3       2.25
19      233000.0         1710         3       2.00
20      937000.0         2450         3       1.75
21      667000.0         1400         3       1.00
22      580500.0         2320         3       2.50
23      687500.0         2330         4       1.75
24      535000.0         1090         3       1.00
25      322500.0         2060         4       2.75
26      696000.0         2300         3       2.50
27      640000.0         2360         4       2.00
28      240000.0         1220         4       1.00
29      605000.0         2620         4       2.50
...          ...          ...       ...        ...
15005   330000.0         1450         3       2.50
15006   608500.0         2850         4       3.50
15007   785000.0         3070         4       3.50
15008   610950.0         1680         3       3.00
15009   399950.0         3087         3       2.50
15010   579000.0         1900         4       3.25
15011   362500.0          940         2       1.50
15012   645000.0         1730         3       3.25
15013   594866.0         2780         3       3.00
15014   490000.0         1500         3       2.25
15015   399950.0          710         2       1.00
15016   270000.0         1870         3       2.50
15017   505000.0         1430         2       2.50
15018   385000.0         1520         3       2.50
15019   414500.0         1210         2       1.50
15020   347500.0         2540         3       2.50
15021  1222500.0         4910         4       3.50
15022  1088000.0         4170         5       3.75
15023   350000.0         2500         4       2.75
15024   679950.0         3600         5       2.75
15025  1575000.0         3410         4       3.25
15026   810000.0         3990         4       3.00
15027  1537000.0         4470         5       3.75
15028   467000.0         1425         3       2.50
15029   507250.0         2270         3       2.50
15030   610685.0         2520         4       2.50
15031  1007500.0         3510         4       3.50
15032   360000.0         1530         3       2.50
15033   400000.0         2310         4       2.50
15034   325000.0         1020         2       0.75

[15035 rows x 4 columns]

In [152]:
xdata = np.array(house2[["sqft_living", "bedrooms", "bathrooms"]])
ydata = np.array(house2[["price"]])
print(xdata.shape)
print(ydata.shape)

(15035, 3)
(15035, 1)


In [153]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.2, random_state=42)

In [157]:
scaler=MinMaxScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [168]:
x = tf.placeholder(tf.float32, shape=[None, 3])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([3, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hf = x @ w + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(0.01).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [170]:
for step in range(200001):
    sess.run(train, feed_dict={x:xtrain, y:ytrain})
    if step % 2000 == 0:
        wv, cv, hv = sess.run([w, cost, hf], feed_dict={x:xtrain, y:ytrain})
        print("step: %s, w: %s, cost: %s, prediction: %s" % (step, wv, cv, hv))

step: 0, w: [[2335410.5 ]
 [ -99198.11]
 [ 916172.75]], cost: 75137960000.0, prediction: [[240183.89]
 [415491.44]
 [588247.3 ]
 ...
 [774605.2 ]
 [275435.34]
 [520138.94]]
step: 2000, w: [[2442282.5 ]
 [-144918.58]
 [ 882360.8 ]], cost: 74400014000.0, prediction: [[242666.61]
 [411795.75]
 [591321.4 ]
 ...
 [779106.94]
 [279531.25]
 [517113.94]]
step: 4000, w: [[2542395.5 ]
 [-185963.17]
 [ 848021.8 ]], cost: 73751040000.0, prediction: [[245123.47]
 [407965.12]
 [594439.1 ]
 ...
 [783312.1 ]
 [283499.25]
 [514090.12]]
step: 6000, w: [[2636375.2 ]
 [-222792.86]
 [ 813701.75]], cost: 73178644000.0, prediction: [[247489.5 ]
 [404038.03]
 [597570.25]
 ...
 [787268.6 ]
 [287283.8 ]
 [511090.34]]
step: 8000, w: [[2724722.5 ]
 [-255863.88]
 [ 779781.7 ]], cost: 72672650000.0, prediction: [[249733.44]
 [400055.28]
 [600688.3 ]
 ...
 [791007.3 ]
 [290861.3 ]
 [508134.53]]
step: 10000, w: [[2807850.5 ]
 [-285603.97]
 [ 746513.06]], cost: 72224540000.0, prediction: [[251844.81]
 [396054.3 ]
 [60

step: 94000, w: [[4075868.5 ]
 [-610014.4 ]
 [ 128852.96]], cost: 68610310000.0, prediction: [[281678.2 ]
 [311990.38]
 [663935.6 ]
 ...
 [851354.9 ]
 [343200.75]
 [450937.25]]
step: 96000, w: [[4082868.5 ]
 [-611389.4 ]
 [ 125084.94]], cost: 68607030000.0, prediction: [[281835.88]
 [311452.12]
 [664310.4 ]
 ...
 [851677.44]
 [343464.06]
 [450604.8 ]]
step: 98000, w: [[4089494.5  ]
 [-612687.3  ]
 [ 121521.016]], cost: 68604070000.0, prediction: [[281984.16]
 [310942.2 ]
 [664665.06]
 ...
 [851983.  ]
 [343712.38]
 [450290.16]]
step: 100000, w: [[4095791.8  ]
 [-613937.3  ]
 [ 118150.695]], cost: 68601446000.0, prediction: [[282123.53]
 [310459.12]
 [664998.9 ]
 ...
 [852271.8 ]
 [343946.8 ]
 [449991.  ]]
step: 102000, w: [[4101791.8  ]
 [-615079.8  ]
 [ 114965.266]], cost: 68599060000.0, prediction: [[282249.12]
 [309996.5 ]
 [665321.9 ]
 ...
 [852554.25]
 [344162.94]
 [449708.5 ]]
step: 104000, w: [[4107320.2 ]
 [-616204.8 ]
 [ 111962.71]], cost: 68596986000.0, prediction: [[282381.3

step: 186000, w: [[4193363.5 ]
 [-633147.94]
 [  65694.97]], cost: 68579647000.0, prediction: [[284317.12]
 [302964.53]
 [670214.9 ]
 ...
 [856767.5 ]
 [347613.16]
 [445361.88]]
step: 188000, w: [[4193863.5  ]
 [-633248.94 ]
 [  65450.254]], cost: 68579623000.0, prediction: [[284325.5]
 [302927.8]
 [670240.5]
 ...
 [856791.7]
 [347629.1]
 [445339.6]]
step: 190000, w: [[4194423.  ]
 [-633357.3 ]
 [  65210.76]], cost: 68579602000.0, prediction: [[284330.28]
 [302888.53]
 [670268.7 ]
 ...
 [856821.5 ]
 [347642.3 ]
 [445316.9 ]]
step: 192000, w: [[4195102.  ]
 [-633482.3 ]
 [  64940.08]], cost: 68579586000.0, prediction: [[284329.56]
 [302838.06]
 [670299.6 ]
 ...
 [856856.2 ]
 [347651.84]
 [445287.25]]
step: 194000, w: [[4195363.   ]
 [-633519.3  ]
 [  64704.848]], cost: 68579574000.0, prediction: [[284347.1 ]
 [302811.88]
 [670319.2 ]
 ...
 [856865.  ]
 [347673.3 ]
 [445270.2 ]]
step: 196000, w: [[4195569.   ]
 [-633521.2  ]
 [  64501.426]], cost: 68579557000.0, prediction: [[284359.66]


In [171]:
hvs = sess.run(hf, feed_dict={x:xtest})

In [172]:
hvs = hvs.reshape(-1)
ytest = ytest.reshape(-1)

In [173]:
comparison = pd.DataFrame({
    "prediction": list(hvs),
    "ytest": list(ytest)
})
comparison

prediction      ytest
0     6.647845e+05   256000.0
1     8.323651e+05   235000.0
2     6.159048e+05   626700.0
3     3.328206e+05   245500.0
4     9.576113e+05   593450.0
5     6.745271e+05   400000.0
6     7.186529e+05   320000.0
7     9.407377e+05   465000.0
8     8.995088e+05   323000.0
9     9.966323e+05   250000.0
10    1.204740e+06   925000.0
11    6.956879e+05   575000.0
12    4.476355e+05   425000.0
13    1.172214e+06   770000.0
14    3.495252e+05   200000.0
15    8.447698e+05   495000.0
16    1.025976e+06   864000.0
17    9.434654e+05   482000.0
18    8.110225e+05   568000.0
19    4.790586e+05   439000.0
20    1.438074e+06   610000.0
21    9.318656e+05   601000.0
22    8.986382e+05   340000.0
23    6.451831e+05   529000.0
24    1.277859e+06   654000.0
25    4.912944e+05   425000.0
26    1.687060e+06  1575000.0
27    1.066855e+06   423000.0
28    6.259325e+05   315000.0
29    8.545124e+05   360000.0
...            ...        ...
2977  1.764298e+06   486000.0
2978  1.114748e+06   380000.0
2979  1.578688e+06   765000.0
2980  9.628851e+05   490000.0
2981  4.846832e+05   254000.0
2982  6.828795e+05   327500.0
2983  1.135220e+06   969000.0
2984  7.292661e+05   260656.0
2985  6.815421e+05   658500.0
2986  1.180216e+06   880000.0
2987  1.891921e+06  1229000.0
2988  6.740074e+05   360000.0
2989  1.474718e+06   859000.0
2990  6.890238e+05   441000.0
2991  1.153600e+06   430000.0
2992  5.676609e+05   420200.0
2993  9.388806e+05   564000.0
2994  5.899901e+05   393000.0
2995  1.149366e+06   875000.0
2996  9.176037e+05   520000.0
2997  6.206588e+05   335000.0
2998  2.329244e+06  2641100.0
2999  7.397608e+05   265000.0
3000  4.275672e+05   304000.0
3001  7.524001e+05   478000.0
3002  8.180374e+05   640500.0
3003  1.110630e+06   795000.0
3004  5.339137e+05   353000.0
3005  8.737630e+05   560000.0
3006  5.324072e+05   510500.0

[3007 rows x 2 columns]

# 연습문제 3

sqft_living, bedrooms, bathrooms, sqrt_lot, floors, zipcode에 따른 price?

In [174]:
house3 = house[["price", "sqft_living", "bedrooms", "bathrooms", "sqft_lot", "floors", "zipcode"]]
house3

price  sqft_living  bedrooms  bathrooms  sqft_lot  floors  zipcode
0       221900.0         1180         3       1.00      5650     1.0    98178
1       180000.0          770         2       1.00     10000     1.0    98028
2       510000.0         1680         3       2.00      8080     1.0    98074
3       257500.0         1715         3       2.25      6819     2.0    98003
4       291850.0         1060         3       1.50      9711     1.0    98198
5       662500.0         3560         3       2.50      9796     1.0    98007
6       468000.0         1160         2       1.00      6000     1.0    98115
7       310000.0         1430         3       1.00     19901     1.5    98028
8       400000.0         1370         3       1.75      9680     1.0    98074
9       530000.0         1810         5       2.00      4850     1.5    98107
10      650000.0         2950         4       3.00      5000     2.0    98126
11      395000.0         1890         3       2.00     14040     2.0    98019
12      485000.0         1600         4       1.00      4300     1.5    98103
13      189000.0         1200         2       1.00      9850     1.0    98002
14      230000.0         1250         3       1.00      9774     1.0    98003
15      385000.0         1620         4       1.75      4980     1.0    98133
16     2000000.0         3050         3       2.75     44867     1.0    98040
17      252700.0         1070         2       1.50      9643     1.0    98030
18      329000.0         2450         3       2.25      6500     2.0    98030
19      233000.0         1710         3       2.00      4697     1.5    98002
20      937000.0         2450         3       1.75      2691     2.0    98119
21      667000.0         1400         3       1.00      1581     1.5    98112
22      580500.0         2320         3       2.50      3980     2.0    98027
23      687500.0         2330         4       1.75      5000     1.5    98117
24      535000.0         1090         3       1.00      3000     1.5    98117
25      322500.0         2060         4       2.75      6659     1.0    98058
26      696000.0         2300         3       2.50      3060     1.5    98115
27      640000.0         2360         4       2.00      6000     2.0    98107
28      240000.0         1220         4       1.00      8075     1.0    98001
29      605000.0         2620         4       2.50      7553     2.0    98056
...          ...          ...       ...        ...       ...     ...      ...
15005   330000.0         1450         3       2.50      5008     1.0    98106
15006   608500.0         2850         4       3.50      5577     2.0    98056
15007   785000.0         3070         4       3.50      4684     2.0    98027
15008   610950.0         1680         3       3.00      1570     3.0    98103
15009   399950.0         3087         3       2.50      5002     2.0    98023
15010   579000.0         1900         4       3.25      2631     2.0    98144
15011   362500.0          940         2       1.50      1768     2.0    98144
15012   645000.0         1730         3       3.25      1229     2.0    98119
15013   594866.0         2780         3       3.00      6000     2.0    98065
15014   490000.0         1500         3       2.25      1290     2.0    98117
15015   399950.0          710         2       1.00      1157     2.0    98102
15016   270000.0         1870         3       2.50      5000     2.0    98042
15017   505000.0         1430         2       2.50      1201     3.0    98107
15018   385000.0         1520         3       2.50      1488     3.0    98125
15019   414500.0         1210         2       1.50      1278     2.0    98117
15020   347500.0         2540         3       2.50      4760     2.0    98038
15021  1222500.0         4910         4       3.50      9444     1.5    98074
15022  1088000.0         4170         5       3.75      8142     2.0    98056
15023   350000.0         2500         4       2.75      5995     2.0    98042
15024   679950.0         3600    

In [175]:
xdata = np.array(house3[["sqft_living", "bedrooms", "bathrooms", "sqft_lot", "floors", "zipcode"]])
ydata = np.array(house3[["price"]])
print(xdata.shape)
print(ydata.shape)

(15035, 6)
(15035, 1)


In [176]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.2, random_state=42)

In [181]:
x = tf.placeholder(tf.float32, shape=[None, 6])
y = tf.placeholder(tf.float32, shape=[None, 1])
w = tf.Variable(tf.random_normal([6, 1]), name="weight")
b = tf.Variable(tf.random_normal([1]), name="bias")

hf = x @ w + b
cost = tf.reduce_mean(tf.square(hf - y))
train = tf.train.GradientDescentOptimizer(1e-10).minimize(cost)

sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [182]:
for step in range(200001):
    sess.run(train, feed_dict={x:xtrain, y:ytrain})
    if step % 10000 == 0:
        wv, cv, hv = sess.run([w, cost, hf], feed_dict={x:xtrain, y:ytrain})
        print("step: %s, w: %s, cost: %s, prediction: %s" % (step, wv, cv, hv))

step: 0, w: [[ 0.7779436 ]
 [-0.32808354]
 [ 0.46059978]
 [ 2.0935388 ]
 [ 3.1908307 ]
 [10.231167  ]], cost: 388719940000.0, prediction: [[1023345.6 ]
 [1008319.25]
 [1029988.1 ]
 ...
 [1013906.8 ]
 [1020801.5 ]
 [1019609.2 ]]
step: 10000, w: [[ 2.3295474e+02]
 [-2.5720575e-01]
 [ 6.0465682e-01]
 [-7.5090490e-02]
 [ 3.2425168e+00]
 [ 5.7176811e-01]], cost: 72959200000.0, prediction: [[295403.1 ]
 [300604.1 ]
 [667966.2 ]
 ...
 [801295.8 ]
 [342078.66]
 [451551.22]]
step: 20000, w: [[ 2.7686594e+02]
 [-2.9821929e-01]
 [ 6.2857682e-01]
 [-2.3435575e-01]
 [ 3.2532511e+00]
 [-3.3666208e-01]], cost: 70603600000.0, prediction: [[250073.44]
 [257297.58]
 [692479.7 ]
 ...
 [852103.9 ]
 [305738.34]
 [435978.47]]
step: 30000, w: [[ 2.8516769e+02]
 [-3.6041719e-01]
 [ 6.2977082e-01]
 [-2.6446608e-01]
 [ 3.2562821e+00]
 [-5.0840592e-01]], cost: 70519440000.0, prediction: [[241503.62]
 [249110.25]
 [697114.2 ]
 ...
 [861709.5 ]
 [298867.97]
 [433034.38]]
step: 40000, w: [[ 2.8672937e+02]
 [-4.2662

In [183]:
hvs = sess.run(hf, feed_dict={x:xtest})

In [184]:
hvs = hvs.reshape(-1)
ytest = ytest.reshape(-1)

In [185]:
comparison = pd.DataFrame({
    "prediction": list(hvs),
    "ytest": list(ytest)
})
comparison

prediction      ytest
0     3.692618e+05   256000.0
1     4.943558e+05   235000.0
2     3.500890e+05   626700.0
3     1.711368e+05   245500.0
4     5.558289e+05   593450.0
5     3.775341e+05   400000.0
6     3.981070e+05   320000.0
7     5.471565e+05   465000.0
8     4.923620e+05   323000.0
9     5.382798e+05   250000.0
10    6.446831e+05   925000.0
11    3.200107e+05   575000.0
12    3.278719e+05   425000.0
13    6.674192e+05   770000.0
14    2.514174e+05   200000.0
15    4.610644e+05   495000.0
16    5.932340e+05   864000.0
17    5.838296e+05   482000.0
18    4.454368e+05   568000.0
19    2.461998e+05   439000.0
20    8.001134e+05   610000.0
21    5.419788e+05   601000.0
22    4.895278e+05   340000.0
23    3.248620e+05   529000.0
24    6.824629e+05   654000.0
25    2.845601e+05   425000.0
26    9.223909e+05  1575000.0
27    6.111253e+05   423000.0
28    3.159992e+05   315000.0
29    4.689526e+05   360000.0
...            ...        ...
2977  9.649308e+05   486000.0
2978  5.980194e+05   380000.0
2979  8.723137e+05   765000.0
2980  5.206848e+05   490000.0
2981  2.483779e+05   254000.0
2982  4.178603e+05   327500.0
2983  6.482036e+05   969000.0
2984  4.076340e+05   260656.0
2985  3.496882e+05   658500.0
2986  6.696303e+05   880000.0
2987  1.018438e+06  1229000.0
2988  4.114115e+05   360000.0
2989  6.666151e+05   859000.0
2990  3.864783e+05   441000.0
2991  6.417566e+05   430000.0
2992  3.233008e+05   420200.0
2993  5.129545e+05   564000.0
2994  4.043777e+05   393000.0
2995  6.192384e+05   875000.0
2996  5.424016e+05   520000.0
2997  3.389463e+05   335000.0
2998  1.279532e+06  2641100.0
2999  4.409108e+05   265000.0
3000  2.188405e+05   304000.0
3001  4.160697e+05   478000.0
3002  4.152412e+05   640500.0
3003  5.940164e+05   795000.0
3004  3.048206e+05   353000.0
3005  4.766407e+05   560000.0
3006  3.087692e+05   510500.0

[3007 rows x 2 columns]