In [18]:
import tensorflow as tf

# 순전파(forward propagation)와 역전파(backpropagation)

## 순전파

In [13]:
class MulLayer:
    
    def __init__(self):
        self.x = None
        self.y = None
        
    def forward(self, x, y):
        self.x = x
        self.y = y
        out = x * y
        return out
    
    def backward(self, dout):
        dx = dout * self.y
        dy = dout * self.x
        return dx, dy

In [14]:
mal = MulLayer()
mtl = MulLayer()

In [15]:
apple = 100
apple_num = 2
tax = 1.1
apple_price = mal.forward(apple, apple_num)
price = mtl.forward(apple_price, tax)
print("price: ", int(price))

price:  220


## 역전파

In [17]:
dprice = 1
dapple_price, dtax = mtl.backward(dprice)
dapple, dapple_num = mal.backward(dapple_price)
print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


# Tensorflow

## Tensorflow 자료형: constant, placeholder, variable

### 상수형(Constant)

constant(): 상수형을 저장할 때 사용하는 함수

In [34]:
a = tf.constant([5], dtype=tf.float32)
b = tf.constant([10], dtype=tf.float32)
c = tf.constant([2], dtype=tf.float32)
c

<tf.Tensor 'Const_16:0' shape=(1,) dtype=float32>

텐서플로우는 그냥 출력하면 각 노드의 정보만 나온다

In [35]:
d = a * b + c
d

<tf.Tensor 'add_1:0' shape=(1,) dtype=float32>

텐서플로우는 노드와 엣지로 구성된다

텐서: 다차원 배열

세션을 생성해서 그래프 실행 (그래프를 실행하려면 세션이 있어야 한다)

세션: 그래프를 실행시켜주는 runner

In [38]:
sess = tf.Session()    # 세션 객체 생성
print(sess.run(d))    # 어떤 노드를 실행할건지를 괄호 안에 써준다
sess.run(d)

[52.]


array([52.], dtype=float32)

### 플레이스 홀더

그래프를 실행시키는 목적: 모델을 만들기 위해서 (모델을 만드는 행위: training)
* 트레이닝을 해서 모델을 만들려면 그래프가 실행되어야만 한다

플레이스 홀더: 학습용 데이터를 저장하기 위한 장소

In [42]:
x = tf.placeholder(dtype=tf.float32)
y = x * 2
sess.run(y)    # 플레이스 홀더에 피딩을 안해줘서 에러가 난다

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float
	 [[node Placeholder_1 (defined at <ipython-input-42-aa25a06ba2e2>:1) ]]

Original stack trace for 'Placeholder_1':
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\user\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "C:\Users\user\Anaconda3\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelapp.py", line 505, in start
    self.io_loop.start()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\platform\asyncio.py", line 148, in start
    self.asyncio_loop.run_forever()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "C:\Users\user\Anaconda3\lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "C:\Users\user\Anaconda3\lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 690, in <lambda>
    lambda f: self._run_callback(functools.partial(callback, future))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 781, in inner
    self.run()
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.send(value)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "C:\Users\user\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "C:\Users\user\Anaconda3\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2848, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2874, in _run_cell
    return runner(coro)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3049, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3214, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "C:\Users\user\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-42-aa25a06ba2e2>", line 1, in <module>
    x = tf.placeholder(dtype=tf.float32)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\array_ops.py", line 2143, in placeholder
    return gen_array_ops.placeholder(dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 7400, in placeholder
    "Placeholder", dtype=dtype, shape=shape, name=name)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 788, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3616, in create_op
    op_def=op_def)
  File "C:\Users\user\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__
    self._traceback = tf_stack.extract_stack()


피딩(feeding): 학습용 데이터를 (딕셔너리 형태로) 전달하는 행위 (그래프를 실행하는 시점에 데이터를 전달해줘야 한다)

In [43]:
x = tf.placeholder(dtype=tf.float32)
y = x * 2
sess.run(y, feed_dict={x:[1, 2, 3, 4]})

array([2., 4., 6., 8.], dtype=float32)

In [44]:
data = [1, 2, 3, 4]
x = tf.placeholder(dtype=tf.float32)
y = x * 2
sess.run(y, feed_dict={x:data})

array([2., 4., 6., 8.], dtype=float32)

### 변수 (Variable)

변수: 훈련(트레이닝/모델링)과정에서 변화하는 기울기, 절편 등

In [48]:
# 그래프 정의
inputData = [1, 2, 3]
x = tf.placeholder(dtype=tf.float32)
w = tf.Variable([2], dtype=tf.float32)
yhat = w * x

# 세션 객체 생성해서 실행
sess = tf.Session()
sess.run(tf.global_variables_initializer())    # 변수는 사용하기에 앞서서 초기화를 해줘야 한다
sess.run(yhat, feed_dict={x:inputData})

array([2., 4., 6.], dtype=float32)

## 그 외

### tf.matmul()

tf.matmul(,) 활용 예제: 행렬곱

In [56]:
x = tf.constant([[1, 2, 3]])
w = tf.constant([[2], [2], [2]])
y = tf.matmul(x,w)
sess.run(y)

array([[12]])

In [55]:
x = tf.Variable([[1, 2, 3]])
w = tf.constant([[2], [2], [2]])
y = tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

array([[12]])

In [58]:
x = tf.Variable([[1, 2, 3], [1, 2, 3], [2, 3, 4]])
w = tf.constant([[2], [2], [2]])
y = tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y)

array([[12],
       [12],
       [18]])

### None

In [64]:
indata = [[1, 2, 3], [1, 2, 3], [2, 3, 4]]
x = tf.placeholder(dtype=tf.float32, shape=[None, 3])
w = tf.constant([[2], [2], [2]], dtype=tf.float32)
y = tf.matmul(x,w)
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:indata})

array([[12.],
       [12.],
       [18.]], dtype=float32)

* 데이터의 크기가 매번 달라질 수 있는데, 위의 경우처럼 None을 써주면 아직 정해지지 않았다는 의미로, 텐서플로우가 알아서 크기를 조절해준다 (행은 미정, 열은 3개이므로 열에 맞춰 행을 지정)

In [65]:
data = [[1, 1, 1], [2, 2, 2]]
x = tf.placeholder(dtype=tf.float32, shape=[None, 3])
w = tf.Variable([[2], [2], [2]], dtype=tf.float32)
b = tf.Variable([4], dtype=tf.float32)
y = tf.matmul(x,w) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(y, feed_dict={x:data})

array([[10.],
       [16.]], dtype=float32)