1. 다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

이 행렬에서 값 5 을 인덱싱한다.

In [1]:
import numpy as np

m = np.array([[ 0, 1, 2, 3, 4], [ 5, 6, 7, 8, 9], [10, 11, 12, 13, 14]])

print(m[1, 0])

5


이 행렬에서 값 14 을 인덱싱한다.

In [2]:
print(m[-1, -1])

14


이 행렬에서 배열 [6, 7] 을 슬라이싱한다.

In [3]:
print(m[1, 1:3])

[6 7]


이 행렬에서 배열 [7, 12] 을 슬라이싱한다.

In [4]:
print(m[1:, 2])

[ 7 12]


이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [5]:
print(m[:2, -2:])

[[3 4]
 [8 9]]


2.다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

이 배열에서 4의 배수를 찾아라.

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[np.where(x%4==0)])

[ 4  8 12 16 20]


이 배열에서 6로 나누면 1이 남는 수를 찾아라.

In [8]:
print(x[np.where(x%6==1)])

[ 1  7 13 19]


이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [18]:
print(x[np.where((x%3==0) & (x%4==1))])

[9]
